#!/bin/sh

# See https://developer.apple.com/library/content/technotes/tn2450
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x7000000E0}]}'
