#!/usr/bin/env bash

set -e

MINIMUM_HAMMERSPOON_VERSION=0.9.54

function version { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

command -v brew > /dev/null || (echo "--- ERROR: Homebrew is required. Get it here: https://brew.sh/" && exit 1)

command -v hs > /dev/null \
    && (killall Hammerspoon && echo "--- Killed Hammerspoon") || echo "--- Hammerspoon is not running" \
    && brew reinstall --build-from-source --force --quiet hammerspoon \
    || (brew install --HEAD --quiet hammerspoon && echo "--- Installed Hammerspoon")

# Prepare Hammerspoon custom settings
mkdir -p "$HOME"/.hammerspoon/Spoons
if ! grep -sq "ControlEscape" "$HOME"/.hammerspoon/init.lua; then
    echo "hs.loadSpoon('ControlEscape'):start() -- Load Hammerspoon bits from https://github.com/jasonrudolph/ControlEscape.spoon" >> "$HOME"/.hammerspoon/init.lua
fi
echo "--- Added settings to Hammerspoon config"

# Open Hammerspoon
open /Applications/Hammerspoon.app

# Enable Hammerspoon at startup
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Hammerspoon.app", hidden:true}' > /dev/null \
    || echo "--- ERROR: failed to enable Hammerspoon autostart"

# Output Hammerspoon version
CURRENT_VERSION="$(brew info --json=v2 hammerspoon | jq '.casks[0].installed')"

if [ "$(version "$CURRENT_VERSION")" -ge "$(version "$MINIMUM_HAMMERSPOON_VERSION")" ]; then
    echo "--- SUCCESS: Hammerspoon $CURRENT_VERSION was installed."
else
    echo "--- ERROR: Hammerspoon version $MINIMUM_HAMMERSPOON_VERSION or greater is required. Actual installed version: $CURRENT_VERSION."
    echo "--- Try running "brew update" and then re-run this script."
    echo "--- If the error persists, open an issue here: https://github.com/jasonrudolph/ControlEscape.spoon"
fi
